# This file is generated by /home/ec2-user/download/numpy-1.10.4/setup.py
# It contains system_info results at the time of building this package.
__all__ = ["get_info","show"]

atlas_3_10_blas_info={}
atlas_3_10_blas_threads_info={}
atlas_threads_info={'extra_link_args': ['-lgfortran -lquadmath'], 'define_macros': [('NO_ATLAS_INFO', -1)], 'language': 'f77', 'runtime_library_dirs': ['/var/task/lib'], 'libraries': ['lapack', 'ptf77blas', 'ptcblas', 'atlas', 'lapack', 'f77blas', 'cblas', 'atlas'], 'library_dirs': ['/usr/lib64/atlas-sse3'], 'include_dirs': ['/usr/include']}
blas_opt_info={'extra_link_args': ['-lgfortran -lquadmath'], 'define_macros': [('HAVE_CBLAS', None), ('NO_ATLAS_INFO', -1)], 'language': 'c', 'runtime_library_dirs': ['/var/task/lib'], 'libraries': ['ptf77blas', 'ptcblas', 'atlas', 'lapack', 'f77blas', 'cblas', 'atlas'], 'library_dirs': ['/usr/lib64/atlas-sse3'], 'include_dirs': ['/usr/include']}
atlas_blas_threads_info={'extra_link_args': ['-lgfortran -lquadmath'], 'define_macros': [('HAVE_CBLAS', None), ('NO_ATLAS_INFO', -1)], 'language': 'c', 'runtime_library_dirs': ['/var/task/lib'], 'libraries': ['ptf77blas', 'ptcblas', 'atlas', 'lapack', 'f77blas', 'cblas', 'atlas'], 'library_dirs': ['/usr/lib64/atlas-sse3'], 'include_dirs': ['/usr/include']}
openblas_info={}
lapack_opt_info={'extra_link_args': ['-lgfortran -lquadmath'], 'define_macros': [('NO_ATLAS_INFO', -1)], 'language': 'f77', 'runtime_library_dirs': ['/var/task/lib'], 'libraries': ['lapack', 'ptf77blas', 'ptcblas', 'atlas', 'lapack', 'f77blas', 'cblas', 'atlas'], 'library_dirs': ['/usr/lib64/atlas-sse3'], 'include_dirs': ['/usr/include']}
openblas_lapack_info={}
atlas_3_10_threads_info={}
atlas_3_10_info={}
lapack_mkl_info={}
blas_mkl_info={}
mkl_info={}

def get_info(name):
    g = globals()
    return g.get(name, g.get(name + "_info", {}))

def show():
    for name,info_dict in globals().items():
        if name[0] == "_" or type(info_dict) is not type({}): continue
        print(name + ":")
        if not info_dict:
            print("  NOT AVAILABLE")
        for k,v in info_dict.items():
            v = str(v)
            if k == "sources" and len(v) > 200:
                v = v[:60] + " ...\n... " + v[-60:]
            print("    %s = %s" % (k,v))
    